# Generated by Django 5.1.1 on 2024-10-01 21:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_productentry_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="productentry",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
