# Generated by Django 5.1.1 on 2024-10-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_productentry_date_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productentry",
            name="condition",
            field=models.CharField(max_length=30),
        ),
    ]
