# Generated by Django 5.1.1 on 2024-10-07 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_productentry_condition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productentry",
            name="date_added",
        ),
    ]
